function t331_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');if(hook!==''){$('.r').on('click','a[href="'+hook+'"]',function(e){t331_showPopup(recid);t331_resizePopup(recid);e.preventDefault();if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t331_setHeight(recid){var el=$("#rec"+recid);var div=el.find(".t331__video-carier");var ratiowidth=div.attr("data-video-width");var ratioheight=div.attr("data-video-height");var ratio=ratioheight/ratiowidth;var height=div.width()*ratio;div.height(height);div.parent().height(height)}
function t331_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t-popup');var youtubeid=el.find(".t331__youtube").attr('data-content-popup-video-url-youtube');var videourl='https://www.youtube.com/embed/'+youtubeid;el.find(".t331__video-carier").html("<iframe id=\"youtubeiframe"+recid+"\" class=\"t331__iframe\" width=\"100.5%\" height=\"100.5%\" src=\""+videourl+"?autoplay=1&rel=0\" frameborder=\"0\" allowfullscreen></iframe>");popup.css('display','block');t331_setHeight(recid);setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed');$('body').addClass('t331__body_popupshowed');el.find('.t-popup').click(function(e){if(e.target==this){t331_popup_close(recid)}});el.find('.t-popup__close').click(function(e){t331_popup_close(recid)});$(document).keydown(function(e){if(e.keyCode==27){t331_popup_close(recid)}})}
function t331_popup_close(recid){$('body').removeClass('t-body_popupshowed');$('body').removeClass('t331__body_popupshowed');$('#rec'+recid+' .t-popup').removeClass('t-popup_show');setTimeout(function(){$("#rec"+recid+" .t331__video-carier").html("");$('#rec'+recid+' .t-popup').not('.t-popup_show').css('display','none')},300)}
function t331_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height(),popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t331_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}
function t391_checkSize(recid){var el=$("#rec"+recid);var cover=el.find('.t-cover');var carrier=el.find('.t-cover__carrier');var filter=el.find('.t-cover__filter');var height=el.find('.t391__firstcol').height()+el.find('.t391__secondcol').height();if(window.matchMedia('(max-width: 960px)').matches&&height>0){cover.css('height',height);carrier.css('height',height);filter.css('height',height)}}
t431_createTable=function(recid,tablehead,tabledata,tablecolsize,hastargetblank,btnstyles,t431__tdstyles,t431__thstyles,t431__oddrowstyles,t431__evenrowstyles){var t431__arrayColSize=t431_parseData(tablecolsize);var t431__arrayHead=t431_parseData(tablehead);var t431__arrayData=t431_parseData(tabledata);var t431__maxcolnumber=t431__findMaxRowLengthInTable(t431__arrayHead,t431__arrayData);var t431__colWidth=t431__setColumnsWidth(t431__arrayColSize,t431__maxcolnumber,recid);if(t431__colWidth[0].myText&&t431__colWidth[0].myText[t431__colWidth[0].myText.length-1]=="%"){for(var i=0;i<t431__colWidth.length;i++){t431__colWidth[i].myText=t431__colWidth[i].myText.slice(0,-1);t431__colWidth[i].myText+="vw"}}
var t431__container=$('#rec'+recid+' .t431 .t-container .t431__table');var t431__htmlTable="";if(t431__arrayHead){t431__htmlTable+=t431__generateHtml(recid,t431__arrayHead,"th",hastargetblank,t431__colWidth,btnstyles,t431__thstyles,null,null,t431__maxcolnumber)}
t431__container.append(t431__htmlTable);t431__htmlTable="";if(t431__arrayData){t431__htmlTable+=t431__generateHtml(recid,t431__arrayData,"td",hastargetblank,t431__colWidth,btnstyles,t431__tdstyles,t431__oddrowstyles,t431__evenrowstyles,t431__maxcolnumber)}
t431__container.append(t431__htmlTable)};function t431_setHeadWidth(recid){if($(window).width()>960){var tBody=$('#rec'+recid+' .t431 .t431__tbody');var tHead=$('#rec'+recid+' .t431 .t431__thead');tBody.css("display","block");tHead.css("display","block");var colWidth=$('#rec'+recid+' .t431 .t431__tbody tr:first').children().map(function(){return $(this).width()});var vBorder="";if($('#rec'+recid+' .t431 .t431__tbody tr td:first').css('border-left-width').length>=3){vBorder=$('#rec'+recid+' .t431 .t431__tbody tr td:first').css('border-left-width').slice(0,-2)}
$('#rec'+recid+' .t431 .t431__thead tr').children().each(function(i,el){if($(el).is(":last-child")){$(el).width(colWidth[i]+(tBody.width()-$('#rec'+recid+' .t431 .t431__tbody tr:first').width()))}else{$(el).width(colWidth[i]+(+vBorder))}})}}
function t431__findMaxRowLengthInTable(arrayHead,arrayData){var headMaxLength=0;var dataMaxLength=0;if(arrayHead){headMaxLength=t431__findMaxRowLengInArray(arrayHead)}
if(arrayData){dataMaxLength=t431__findMaxRowLengInArray(arrayData)}
if(dataMaxLength>headMaxLength){return dataMaxLength}else{return headMaxLength}}
function t431__findMaxRowLengInArray(curArray){var maxLength=0;for(var i=0;i<curArray.length;i++){if(curArray[i].length>maxLength){maxLength=curArray[i].length}}
return maxLength}
function t431__setColumnsWidth(colWidth,colsNumber,recid){if(colWidth){return colWidth[0]}else{var tableWidth=$('#rec'+recid+' .t431 .t-container .t-col').width();return(tableWidth/colsNumber+"px")}}
t431__generateHtml=function(recid,arrayValues,coltag,hastargetblank,colWidth,btnstyles,colstyles,oddrowstyles,evenrowstyles,maxcolnumber){var t431__htmlpart="";if(coltag=="td"){var t431__theadorbodytag="tbody"}else{var t431__theadorbodytag="thead"}
t431__htmlpart+="<"+t431__theadorbodytag+" class=\"t431__"+t431__theadorbodytag+"\">";if($('#rec'+recid+' .t431 .t-container .t431__thead th').length>0&&$('#rec'+recid+' .t431 .t-container .t431__thead th').css("border-bottom-width")[0]!="0"){var t431__firstbodyrowstyle="border-top: 0 !important;"}
for(var i=0;i<arrayValues.length;i++){if(coltag=="td"){if((i+1)%2>0){t431__htmlpart+="<tr class=\"t431__oddrow\""+"style=\""+oddrowstyles+"\">"}else{t431__htmlpart+="<tr class=\"t431__evenrow\""+"style=\""+evenrowstyles+"\">"}}else{t431__htmlpart+="<tr>"}
var t431__addingcols=0;if(arrayValues[i].length<maxcolnumber){t431__addingcols=maxcolnumber-arrayValues[i].length}
for(var j=0;j<(arrayValues[i].length+t431__addingcols);j++){if(arrayValues[i][j]){if(Array.isArray(colWidth)&&colWidth[j]){var t431__curWidth=colWidth[j].myText}else{var t431__curWidth=colWidth}
if(i==0&&coltag=="td"){var t431__colwithattr="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+t431__firstbodyrowstyle+"\">"}else{var t431__colwithattr="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+"\">"}
if(arrayValues[i][j].myHref){var t431__tblank="";if(hastargetblank){var t431__tblank="target=\"_blank\""}
if(arrayValues[i][j].myHrefType=="link"){var t431__linkwithattr="<a href=\""+arrayValues[i][j].myHref+"\""+t431__tblank+">";var t431__linkclosetag="</a>"}else{var t431__linkwithattr="<div class=\"t431__btnwrapper\"><a href=\""+arrayValues[i][j].myHref+"\""+t431__tblank+" class=\"t-btn t-btn_sm\" style=\""+btnstyles+"\"><table style=\"width:100%; height:100%;\"><tr><td>";var t431__linkclosetag="</td></tr></table></a></div>"}
t431__htmlpart+=t431__colwithattr+t431__linkwithattr+arrayValues[i][j].myText+t431__linkclosetag+"</"+coltag+">"}else{t431__htmlpart+=t431__colwithattr+arrayValues[i][j].myText+"</"+coltag+">"}}else{t431__htmlpart+="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+"\">"+"</"+coltag+">"}}
t431__htmlpart+="</tr>"}
t431__htmlpart+="</"+t431__theadorbodytag+">";return t431__htmlpart};function t431_parseData(data){if(data!==""&&typeof data!="undefined"){data=t431__addBrTag(data);var arrayTable=[];var arrayRow=[];var curItem={myText:"",myHref:"",myHrefType:""};var hasLink="";var hasLinkWithSpace="";var hasBtn="";var hasBtnWithSpace="";var endLine="";for(var i=0;i<data.length;i++){if(data[i]==";"&&!(data.slice(i-4,i)=="&lt;"||data.slice(i-4,i)=="&gt;"||data.slice(i-5,i)=="&amp;"||data.slice(i-6,i)=="&nbsp;")){arrayRow.push(curItem);curItem={myText:"",myHref:""};hasLink="";hasLinkWithSpace="";hasBtn="";hasBtnWithSpace=""}else{if(hasLink=="link="||hasLinkWithSpace==" link="||hasBtn=="button="||hasBtnWithSpace==" button="){if(curItem.myHref===""&&hasLink==="link="){curItem.myText=curItem.myText.slice(0,-5);curItem.myHrefType="link"}else{if(curItem.myHref===""&&hasLinkWithSpace===" link="){curItem.myText=curItem.myText.slice(0,-6);curItem.myHrefType="link"}else{if(curItem.myHref===""&&hasBtn==="button="){curItem.myText=curItem.myText.slice(0,-7);curItem.myHrefType="btn"}else{if(curItem.myHref===""&&hasBtnWithSpace===" button="){curItem.myText=curItem.myText.slice(0,-8);curItem.myHrefType="btn"}}}}
curItem.myHref+=(data[i])}else{curItem.myText+=(data[i]);hasLink=t431__checkSubstr("link=",hasLink,data[i]);hasLinkWithSpace=t431__checkSubstr(" link=",hasLinkWithSpace,data[i]);hasBtn=t431__checkSubstr("button=",hasBtn,data[i]);hasBtnWithSpace=t431__checkSubstr(" button=",hasBtnWithSpace,data[i])}
endLine=t431__checkSubstr("<br />",endLine,data[i]);if(endLine=="<br />"){if(curItem.myHref){curItem.myHref=curItem.myHref.slice(0,-6)}else{curItem.myText=curItem.myText.slice(0,-6)}
arrayRow.push(curItem);arrayTable.push(arrayRow);curItem={myText:"",myHref:""};hasLink="";hasLinkWithSpace="";hasBtn="";hasBtnWithSpace="";arrayRow=[]}}}
if(arrayRow.length>0||curItem.myText!==""){if(curItem!==""){arrayRow.push(curItem)}
arrayTable.push(arrayRow)}}
return arrayTable}
function t431__checkSubstr(targetSubstr,curSubstr,curSymbol){if(!curSubstr&&curSymbol==targetSubstr[0]){return curSymbol}else{if(curSubstr){for(var i=0;i<(targetSubstr.length-1);i++){if(curSubstr[curSubstr.length-1]==targetSubstr[i]&&curSymbol==targetSubstr[i+1]){return(curSubstr+=curSymbol)}}}}}
function t431__addBrTag(oldStringItem){var newStringItem="";for(var i=0;i<oldStringItem.length;i++){if(oldStringItem[i]=="\n"||oldStringItem[i]=="\r"){newStringItem+="<br />"}else{newStringItem+=oldStringItem[i]}}
return newStringItem}
function t456_setListMagin(recid,imglogo){if($(window).width()>980){var t456__menu=$('#rec'+recid+' .t456');var t456__leftpart=t456__menu.find('.t456__leftwrapper');var t456__listpart=t456__menu.find('.t456__list');if(imglogo){t456__listpart.css("margin-right",t456__leftpart.width())}else{t456__listpart.css("margin-right",t456__leftpart.width()+30)}}}
function t456_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t456__list_item a[href='"+url+"']").addClass("t-active");$(".t456__list_item a[href='"+url+"/']").addClass("t-active");$(".t456__list_item a[href='"+pathname+"']").addClass("t-active");$(".t456__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t456__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t456__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t456_checkAnchorLinks(recid){if($(window).width()>=960){var t456_navLinks=$("#rec"+recid+" .t456__list_item a:not(.tooltipstered)[href*='#']");if(t456_navLinks.length>0){t456_catchScroll(t456_navLinks)}}}
function t456_catchScroll(t456_navLinks){var t456_clickedSectionId=null,t456_sections=new Array(),t456_sectionIdTonavigationLink=[],t456_interval=100,t456_lastCall,t456_timeoutId;t456_navLinks=$(t456_navLinks.get().reverse());t456_navLinks.each(function(){var t456_cursection=t456_getSectionByHref($(this));if(typeof t456_cursection.attr("id")!="undefined"){t456_sections.push(t456_cursection)}
t456_sectionIdTonavigationLink[t456_cursection.attr("id")]=$(this)});$(window).bind('resize',t_throttle(function(){t456_updateSectionsOffsets(t456_sections)},200));$('.t456').bind('displayChanged',function(){t456_updateSectionsOffsets(t456_sections)});setInterval(function(){t456_updateSectionsOffsets(t456_sections)},5000);setTimeout(function(){t456_updateSectionsOffsets(t456_sections);t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId)},1000);t456_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t456_navLinks.removeClass('t-active');t456_sectionIdTonavigationLink[t456_getSectionByHref($(this)).attr("id")].addClass('t-active');t456_clickedSectionId=t456_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t456_now=new Date().getTime();if(t456_lastCall&&t456_now<(t456_lastCall+t456_interval)){clearTimeout(t456_timeoutId);t456_timeoutId=setTimeout(function(){t456_lastCall=t456_now;t456_clickedSectionId=t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId)},t456_interval-(t456_now-t456_lastCall))}else{t456_lastCall=t456_now;t456_clickedSectionId=t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId)}})}
function t456_updateSectionsOffsets(sections){$(sections).each(function(){var t456_curSection=$(this);t456_curSection.attr("data-offset-top",t456_curSection.offset().top)})}
function t456_getSectionByHref(curlink){var t456_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t456_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t456_curLinkValue.substring(1)+"']")}}
function t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId){var t456_scrollPosition=$(window).scrollTop(),t456_valueToReturn=t456_clickedSectionId;if(t456_sections.length!=0&&t456_clickedSectionId==null&&t456_sections[t456_sections.length-1].attr("data-offset-top")>(t456_scrollPosition+300)){t456_navLinks.removeClass('t-active');return null}
$(t456_sections).each(function(e){var t456_curSection=$(this),t456_sectionTop=t456_curSection.attr("data-offset-top"),t456_id=t456_curSection.attr('id'),t456_navLink=t456_sectionIdTonavigationLink[t456_id];if(((t456_scrollPosition+300)>=t456_sectionTop)||(t456_sections[0].attr("id")==t456_id&&t456_scrollPosition>=$(document).height()-$(window).height())){if(t456_clickedSectionId==null&&!t456_navLink.hasClass('t-active')){t456_navLinks.removeClass('t-active');t456_navLink.addClass('t-active');t456_valueToReturn=null}else{if(t456_clickedSectionId!=null&&t456_id==t456_clickedSectionId){t456_valueToReturn=null}}
return!1}});return t456_valueToReturn}
function t456_setPath(){}
function t456_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t456").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t456").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t456_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t456").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t456_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t456").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t456_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t456"),burger=el.find(".t456__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t456_opened")});$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t504_unifyHeights(recid){$('#rec'+recid+' .t504 .t-container').each(function(){var t504__highestBox=0;$('.t504__col',this).each(function(){var t504__curcol=$(this);var t504__curcolchild=t504__curcol.find('.t504__col-wrapper');if(t504__curcol.height()<t504__curcolchild.height())t504__curcol.height(t504__curcolchild.height());if(t504__curcol.height()>t504__highestBox)t504__highestBox=t504__curcol.height()});if($(window).width()>=960){$('.t504__col',this).css('height',t504__highestBox)}else{$('.t504__col',this).css('height',"auto")}})};function t505__createPieChart(recid,data1,data2,data3,data4,sectorcolor,piebgcolor,bgcolor,blocksnumber,diagramwidth,diameter){if(diameter>300||diameter==""||diameter<100){if(diameter==""){var t505__radius=100;diameter=200}
if(diameter>300){var t505__radius=150;diameter=300}
if(diameter<100){var t505__radius=50;diameter=100}}else{var t505__radius=diameter/2}
if(diagramwidth==""){diagramwidth=10}
if(diagramwidth>t505__radius){diagramwidth=10}
if(diagramwidth<1){diagramwidth=1}
if(window.devicePixelRatio>=2){var t505__oldsize=diameter;t505__radius=t505__radius*2;diameter=diameter*2;diagramwidth=diagramwidth*2}
var t505__correction=+diagramwidth/2;var t505__dataarray=[data1,data2,data3,data4];for(var i=0;i<4;i++){if(t505__dataarray[i]!=""&&blocksnumber>i){var t505__canvas=document.querySelector('#rec'+recid+' .t505__pie'+(i+1));t505__canvas.setAttribute("width",diameter);t505__canvas.setAttribute("height",diameter);var t505__context=t505__canvas.getContext("2d");if(window.devicePixelRatio>=2){t505__canvas.style.width=t505__oldsize+"px";t505__canvas.style.height=t505__oldsize+"px"}
for(var j=0;j<2;j++){if(j==1&&t505__dataarray[i]==0){continue}
if(j==0){t505__context.strokeStyle=piebgcolor;var t505__angle=Math.PI*2;t505__context.lineWidth=diagramwidth-1}else{t505__context.strokeStyle=sectorcolor;var t505__angle=Math.PI*2*(t505__dataarray[i]/100);t505__context.lineWidth=diagramwidth}
t505__context.beginPath();t505__context.lineCap="round";t505__context.moveTo(diameter-t505__correction,t505__radius);t505__context.arc(t505__radius,t505__radius,t505__radius-t505__correction,0,t505__angle,!1);t505__context.stroke()}}}}
function t552_init(recid,ratio){var t552__el=$("#rec"+recid),t552__image=t552__el.find(".t552__blockimg:first");t552__setHeight(recid,t552__image,ratio);var t552__doResize;$(window).resize(function(){clearTimeout(t552__doResize);t552__doResize=setTimeout(function(){t552__setHeight(recid,t552__image,ratio)},200)})}
function t552__setHeight(recid,image,ratio){$("#rec"+recid+" .t552__blockimg").css("height",Math.round(image.innerWidth()*ratio))}
function t650_unifyHeights(recid){if($(window).width()>=960){$('#rec'+recid+' .t650 .t-container .t650__row').each(function(){var t650_highestBox=0,t650_currow=$(this);$('.t650__inner-col',this).each(function(){var t650_curCol=$(this),t650_curText=t650_curCol.find(".t650__text"),t650_curBtn=t650_curCol.find(".t650__btn-container"),t650_curColHeight=t650_curText.outerHeight()+t650_curBtn.outerHeight();if(t650_curColHeight>t650_highestBox){t650_highestBox=t650_curColHeight}});$('.t650__inner-col',this).css('height',t650_highestBox)})}else{$('.t650__inner-col').css('height','auto')}}
function t698_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t698_onSuccess(t698_form){var t698_inputsWrapper=t698_form.find('.t-form__inputsbox');var t698_inputsHeight=t698_inputsWrapper.height();var t698_inputsOffset=t698_inputsWrapper.offset().top;var t698_inputsBottom=t698_inputsHeight+t698_inputsOffset;var t698_targetOffset=t698_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t698_target=t698_targetOffset-200}else{var t698_target=t698_targetOffset-100}
if(t698_targetOffset>$(window).scrollTop()||($(document).height()-t698_inputsBottom)<($(window).height()-100)){t698_inputsWrapper.addClass('t698__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t698_target},400);setTimeout(function(){t698_inputsWrapper.addClass('t698__inputsbox_hidden')},400)}
var successurl=t698_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t702_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');if(hook!==''){$('.r').on('click','a[href="'+hook+'"]',function(e){t702_showPopup(recid);t702_resizePopup(recid);e.preventDefault();if(window.lazy=='y'){t_lazyload_update()}
if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t702_onSuccess(t702_form){var t702_inputsWrapper=t702_form.find('.t-form__inputsbox');var t702_inputsHeight=t702_inputsWrapper.height();var t702_inputsOffset=t702_inputsWrapper.offset().top;var t702_inputsBottom=t702_inputsHeight+t702_inputsOffset;var t702_targetOffset=t702_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t702_target=t702_targetOffset-200}else{var t702_target=t702_targetOffset-100}
if(t702_targetOffset>$(window).scrollTop()||($(document).height()-t702_inputsBottom)<($(window).height()-100)){t702_inputsWrapper.addClass('t702__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t702_target},400);setTimeout(function(){t702_inputsWrapper.addClass('t702__inputsbox_hidden')},400)}
var successurl=t702_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t702_lockScroll(){var body=$("body");if(!body.hasClass('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop;body.addClass('t-body_scroll-locked');body.css("top","-"+bodyScrollTop+"px");body.attr("data-popup-scrolltop",bodyScrollTop)}}
function t702_unlockScroll(){var body=$("body");if(body.hasClass('t-body_scroll-locked')){var bodyScrollTop=$("body").attr("data-popup-scrolltop");body.removeClass('t-body_scroll-locked');body.css("top","");body.removeAttr("data-popup-scrolltop")
window.scrollTo(0,bodyScrollTop)}}
function t702_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t-popup');popup.css('display','block');el.find('.t-range').trigger('popupOpened');if(window.lazy=='y'){t_lazyload_update()}
setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){setTimeout(function(){t702_lockScroll()},500)}
el.find('.t-popup').mousedown(function(e){var windowWidth=$(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t702_closePopup(recid)}});el.find('.t-popup__close').click(function(e){t702_closePopup(recid)});el.find('a[href*="#"]').click(function(e){var url=$(this).attr('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup(recid);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t702_closePopup(recid)}})}
function t702_closePopup(recid){$('body').removeClass('t-body_popupshowed t702__body_popupshowed');$('#rec'+recid+' .t-popup').removeClass('t-popup_show');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t702_unlockScroll()}
setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t702_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height()-120,popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t702_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t826_init(recid){t826_startAnimation(recid);var t826__smartResize;window.addEventListener("resize",function(){if(!$isMobile){clearTimeout(t826__smartResize);t826__smartResize=setTimeout(function(){$("div:not(.t826__animation) > div[data-galaxy-id="+recid+"]").remove();t826_startAnimation(recid)},500)}},!1);window.addEventListener("orientationchange",function(){if($isMobile){clearTimeout(t826__smartResize);t826__smartResize=setTimeout(function(){$("div:not(.t826__animation) > div[data-galaxy-id="+recid+"]").remove();t826_startAnimation(recid)},500)}},!1);$('.t826').bind('displayChanged',function(){$("div:not(.t826__animation) > div[data-galaxy-id="+recid+"]").remove();t826_startAnimation(recid)})}
function t826_startAnimation(recid){var el=$("#rec"+recid);var GalaxyEl=el.find(".t826__galaxy");var wr=el.find(".t826");var recs=wr.attr("data-galaxy-rec-ids");var wholepage=wr.attr("data-galaxy-whole-page");var vertFlip=wr.attr("data-galaxy-vflip");var color=wr.attr("data-element-color");var opacity=wr.attr("data-element-opacity");var options={'color':(color===""?"#fff":color),'opacity':(opacity===""?1:opacity.replace(/^0?.([0-9])0?$/g,".$1"))};if(options.color.indexOf('#')!==-1){var color=options.color;if(color[1]===color[2]&&color[3]===color[4]&&color[5]===color[6]){options.color="#"+color[1]+color[3]+color[5]}}
if(vertFlip==="yes"){GalaxyEl.addClass("t826__galaxy_flip")}
if($("#allrecords").attr("data-tilda-mode")==="edit"){t826_addAnimation(el.find(".t826__demo"),GalaxyEl,options);return}
if(typeof recs!=="undefined"){recs=recs.split(",");recs.forEach(function(rec,index,array){var curRec=$("#rec"+rec);var curGalaxyEl=GalaxyEl.clone().css("position","absolute");t826_addAnimation(curRec,curGalaxyEl,options)})}else{var nextBlock=el.next(":has(.t-cover)");var prevBlock=el.prev(":has(.t-cover)");var curGalaxyEl=GalaxyEl.clone().css("position","absolute");if(nextBlock.length!==0){t826_addAnimation(nextBlock,curGalaxyEl,options)}else if(prevBlock.length!==0){t826_addAnimation(prevBlock,curGalaxyEl,options)}}
if(wholepage==="yes"){el.find(".t826__animation").css("display","block");t826_addAnimation($("#allrecords"),GalaxyEl.css("position","fixed"),options)}}
function t826_addAnimation(curRec,GalaxyEl,options){curRec.attr("data-animationappear","off").removeClass('r_hidden');var curRecType=curRec.attr("data-record-type");var curRecId=curRec.attr("id");if(curRecType==="396"){curRec.find(".t396__filter").after(GalaxyEl);GalaxyEl.css("z-index","0")}else if(curRecId==="allrecords"){GalaxyEl.css("z-index","-1")}else{var coverWrapper=curRec.find(".t-cover");if(coverWrapper.length>0){coverWrapper.find(".t-cover__filter").after(GalaxyEl);GalaxyEl.css("z-index","0")}else{var wrapper=curRec;if(wrapper.length===0){return!0}
wrapper.append(GalaxyEl);wrapper.css("position","relative");wrapper.children("div").first().css({"position":"relative","z-index":"1"});if(curRecType=="734"||curRecType=="675"){return}
GalaxyEl.css("z-index","0");if(curRecType=="754"||curRecType=="776"||curRecType=="778"||curRecType=="786"){wrapper.children("div").first().css({"z-index":""});GalaxyEl.css("z-index","-1")}}}
t826_runningAnimation(curRec,options)}
function t826_runningAnimation(curRec,options){var starsSetting;if(!window.isMobile){starsSetting=[{name:"near",count:100,speed:50},{name:"mid",count:200,speed:100},{name:"far",count:700,speed:150}]}else{starsSetting=[{name:"near",count:25,speed:50},{name:"mid",count:500,speed:100},{name:"far",count:175,speed:150}]}
var curRecId=curRec.attr("id");var maxHeight=curRec.outerHeight();var maxWidth=curRec.outerWidth();if(typeof curRecId==="undefined"){curRecId="demo"}else if(curRecId==="allrecords"){maxHeight=$(window).height();maxWidth=$(window).width()}
var animationName="t826__galaxy-"+curRecId;curRec.find("#"+animationName).remove();var newStyle=document.createElement("style");newStyle.id=animationName;newStyle.innerHTML="@keyframes "+animationName+"{"+"to{"+"transform:translateY("+(-maxHeight)+"px)"+"}"+"}";starsSetting.forEach(function(value,index,array){var x=Math.round(Math.random()*maxHeight);var y=Math.round(Math.random()*maxWidth);var dot="";if(options.color.indexOf('#')!==-1){dot=x+"px "+y+"px"}else{if(options.opacity<1){dot=x+"px "+y+"px rgba("+options.color+","+options.opacity+")"}else{dot=x+"px "+y+"px rgb("+options.color+")"}}
var countDots=Math.round(array[index].count*maxHeight/2000);for(var i=0;i<countDots;i++){var x=Math.round(Math.random()*maxWidth);var y=Math.round(Math.random()*maxHeight);if(options.color.indexOf('#')!==-1){dot+=", "+x+"px "+y+"px";dot+=", "+x+"px "+(y+maxHeight)+"px"}else{if(options.opacity<1){dot+=", "+x+"px "+y+"px rgba("+options.color+","+options.opacity+")";dot+=", "+x+"px "+(y+maxHeight)+"px rgba("+options.color+","+options.opacity+")"}else{dot+=", "+x+"px "+y+"px rgb("+options.color+")";dot+=", "+x+"px "+(y+maxHeight)+"px rgb("+options.color+")"}}}
var animationDuration=Math.round(array[index].speed*maxHeight/2000);className="t826__galaxy-"+array[index].name+"-"+curRecId;newStyle.innerHTML+="."+className+":after, ."+className+"{"+"box-shadow:"+dot+";"+"animation-duration:"+animationDuration+"s;"+"animation-name:"+animationName+";"+(options.color.indexOf('#')!==-1?"color:"+options.color+";":"")+(options.color.indexOf('#')!==-1&&options.opacity<1?"opacity:"+options.opacity:"")+"}"+"."+className+":after{"+"content:' ';"+"position:absolute;"+"top:"+maxHeight+"px"+"}";curRec.find(".t826__galaxy > .t826__galaxy-wrapper > .t826__galaxy-"+array[index].name).addClass(className)});curRec.prepend(newStyle);curRec.find(".t826__galaxy > .t826__galaxy-wrapper").css("animation-name","t826__galaxy-fadeIn")}
function t830_init(recid){var rec=$('#rec'+recid);var allrecords=$("#allrecords");var el=rec.find('.t830');var panel=rec.find('.t830__panel');var overlay=rec.find('.t830m__overlay');var menu=rec.find('.t830m');var submenu=rec.find('.t830m__submenu');var burger=rec.find('.t830__side .t830__burger');var menuItem=rec.find('.t830m__list-title a');var submenuItem=rec.find('.t830m__submenu-item a');if($(window).width()>1259){$('.t-body').prepend(rec);allrecords.addClass('t830__allrecords');$('.t-tildalabel').addClass('t830__t-tildalabel')}
t830_initMenu(rec,menu,burger);t830_removePadding(rec,allrecords);t830_calcCol(rec,menu,allrecords);t830_menuHighlight();t830_submenuHighlight();t830_openSubmenu(rec);t830_hoverShowMenu(rec,menu,panel,overlay,burger);$(window).resize(function(){t830_calcCol(rec,menu,allrecords);t830_removePadding(rec,allrecords);if(menu.hasClass('t830m_close')&&$(window).width()>1499){overlay.removeClass('t830m__menu_show')}});if(submenu.hasClass('t830m__submenu_close')){t830_toggleMenu(rec,submenu)}
if($(window).width()>1259){t830_scrollSideMenu(rec)}
menuItem.click(function(){if(window.location.hash.length!=0){menuItem.removeClass('t-active');$(this).addClass('t-active')}});submenuItem.click(function(){if(window.location.hash.length!=0){submenuItem.removeClass('t-active');$(this).addClass('t-active')}});t830_checkAnchorLinks(recid)}
function t830_calcCol(rec,menu,allrecords){if($(window).width()>1259&&!menu.hasClass('t830m_open')){allrecords.addClass('t830__allrecords_padd');$('.t-tildalabel').addClass('t830__t-tildalabel_padd')}
if($(window).width()>1259&&menu.hasClass('t830m_open')){allrecords.addClass('t830__allrecords_padd-small');$('.t-tildalabel').addClass('t830__t-tildalabel_padd-small')}}
function t830_toggleMenu(rec,submenu){var listTitle=rec.find('.t830m__list-title_toggle');var submenu;var textTitle;listTitle.click(function(){submenu=$(this).next();textTitle=$(this).find('.t830m__list-title-text');submenu.slideToggle('slow');textTitle.toggleClass('t830m__list-title-text_opacity');textTitle.toggleClass('t-menu__link-item')})}
function t830_openSubmenu(rec){var submenuItem=rec.find('.t830m__submenu-item a.t-active');submenuItem.parents('.t830m__submenu').css('display','block')}
function t830_hoverShowMenu(rec,menu,panel,overlay,burger){if($(window).width()>1259&&panel.hasClass('t830__panel_hover')){panel.mouseenter(function(e){menu.addClass('t830m__menu_show');burger.addClass('t830__burger_open');overlay.addClass('t830m__overlay_hover')});menu.mouseleave(function(){menu.removeClass('t830m__menu_show');burger.removeClass('t830__burger_open')});overlay.mouseenter(function(){menu.removeClass('t830m__menu_show');burger.removeClass('t830__burger_open');overlay.removeClass('t830m__overlay_hover')})
menu.find('a').on('click',function(){menu.removeClass('t830m__menu_show');burger.removeClass('t830__burger_open')});burger.click(function(){if(burger.hasClass('t830__burger_open')){t830_closeMenu(rec,menu);burger.removeClass('t830__burger_open')}else{menu.addClass('t830m__menu_show');burger.addClass('t830__burger_open');overlay.addClass('t830m__overlay_hover')}})}}
function t830_showMenu(rec,menu,burger){var panel=rec.find('.t830__panel');$('body').addClass('t830__body_menushowed');rec.find('.t830m').addClass('t830m__menu_show');rec.find('.t830m__overlay').addClass('t830m__menu_show');rec.find('.t830m__overlay, .t830m__close, a[href*=#]').click(function(){if($(this).is('.tooltipstered, .t794__tm-link')){return}
t830_closeMenu(rec,menu);burger.removeClass('t830__burger_open')});panel.addClass('t830__panel_close');$(document).keydown(function(e){if(e.keyCode==27){if($('.t-site-search-popup__background').length===0){$('body').removeClass('t830__body_menushowed');$('.t830m').removeClass('t830m__menu_show');burger.removeClass('t830__burger_open');$('.t830m__overlay').removeClass('t830m__menu_show')}}})}
function t830_closeMenu(rec,menu){var panel=rec.find('.t830__panel');if(menu.hasClass('t830m_open')&&$(window).width()<1500){panel.removeClass('t830__panel_close')}
$('body').removeClass('t830__body_menushowed');$('.t830m').removeClass('t830m__menu_show');$('.t830m__overlay').removeClass('t830m__menu_show')}
function t830_initMenu(rec,menu,burger){var obj=rec.find('.t830__menu__content');var panel=rec.find('.t830__panel');var menu=rec.find('.t830m');if(panel.hasClass('t830__panel_click')||(panel.hasClass('t830__panel_hover')&&$(window).width()<=1259)){obj.click(function(e){if(menu.hasClass('t830m__menu_show')){burger.removeClass('t830__burger_open');t830_closeMenu(rec,menu)}else{burger.addClass('t830__burger_open');t830_showMenu(rec,menu,burger)}
e.preventDefault()})}
$('.t830').bind('clickedAnchorInTooltipMenu',function(){t830_closeMenu(rec,menu)})}
function t830_menuHighlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=='/'){pathname=pathname.slice(1)}
if(pathname==''){pathname='/'}
$(".t830m__list-title a[href='"+url+"']").addClass('t-active');$(".t830m__list-title a[href='"+url+"/']").addClass('t-active');$(".t830m__list-title a[href='"+pathname+"']").addClass('t-active');$(".t830m__list-title a[href='/"+pathname+"']").addClass('t-active');$(".t830m__list-title a[href='"+pathname+"/']").addClass('t-active');$(".t830m__list-title a[href='/"+pathname+"/']").addClass('t-active')}
function t830_submenuHighlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=='/'){pathname=pathname.slice(1)}
if(pathname==''){pathname="/"}
$(".t830m__submenu-item a[href='"+url+"']").addClass('t-active');$(".t830m__submenu-item a[href='"+url+"/']").addClass('t-active');$(".t830m__submenu-item a[href='"+pathname+"']").addClass('t-active');$(".t830m__submenu-item a[href='/"+pathname+"']").addClass('t-active');$(".t830m__submenu-item a[href='"+pathname+"/']").addClass('t-active');$(".t830m__submenu-item a[href='/"+pathname+"/']").addClass('t-active')}
function t830_scrollSideMenu(rec){var container=rec.find('.t830m__container');container.on('scroll wheel DOMMouseScroll mousewheel',function(e){var searchResultContainer=rec.find('.t-site-search-dm');if(searchResultContainer.length==0){t830_stopScroll(this,e)}})}
function t830_stopScroll(block,eventScroll){var $this=$(block);var scrollTop=block.scrollTop;var scrollHeight=block.scrollHeight;var height=$this.height();var delta=(eventScroll.type=='DOMMouseScroll'?eventScroll.originalEvent.detail*-40:eventScroll.originalEvent.wheelDelta);var up=delta>0;var prevent=function(){eventScroll.stopPropagation();eventScroll.preventDefault();eventScroll.returnValue=!1;return!1}
if(!up&&-delta>scrollHeight-height-scrollTop){$this.scrollTop(scrollHeight);return prevent()}else if(up&&delta>scrollTop){$this.scrollTop(0);return prevent()}}
function t830_removePadding(rec,allrecords){if(rec.css('display')=='none'){allrecords.css('padding-left',0);$('.t-tildalabel').css('padding-left',0)}}
function t830_checkAnchorLinks(recid){if($(window).width()>=960){var submenuNavLinks=$("#rec"+recid+" .t830m__list a:not(.tooltipstered)[href*='#']");if(submenuNavLinks.length>0){setTimeout(function(){t830_catchScroll(submenuNavLinks,recid)},500)}}}
function t830_catchScroll(navLinks,recid){var rec=$('#rec'+recid);var clickedSectionId=null;var sections=new Array();var sectionIdTonavigationLink=[];var interval=100;var lastCall;var timeoutId;var navLinks=$(navLinks.get().reverse());navLinks.each(function(){var cursection=t830_getSectionByHref($(this));if(typeof cursection.attr('id')!='undefined'){sections.push(cursection)}
sectionIdTonavigationLink[cursection.attr('id')]=$(this)});t830_updateSectionsOffsets(sections);sections.sort(function(a,b){return b.attr('data-offset-top')-a.attr('data-offset-top')});$(window).bind('resize',t_throttle(function(){t830_updateSectionsOffsets(sections)},200));$('.t830').bind('displayChanged',function(){t830_updateSectionsOffsets(sections)});setInterval(function(){t830_updateSectionsOffsets(sections)},5000);t830_highlightNavLinks(navLinks,sections,sectionIdTonavigationLink,clickedSectionId);navLinks.click(function(){var clickedSection=t830_getSectionByHref($(this));if(!$(this).hasClass('tooltipstered')&&typeof clickedSection.attr('id')!='undefined'){navLinks.removeClass('t-active');$(this).addClass('t-active');clickedSectionId=t830_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var now=new Date().getTime();if(lastCall&&now<(lastCall+interval)){clearTimeout(timeoutId);timeoutId=setTimeout(function(){lastCall=now;clickedSectionId=t830_highlightNavLinks(navLinks,sections,sectionIdTonavigationLink,clickedSectionId)},interval-(now-lastCall))}else{lastCall=now;clickedSectionId=t830_highlightNavLinks(navLinks,sections,sectionIdTonavigationLink,clickedSectionId)}})}
function t830_getSectionByHref(curlink){var curLinkValue=curlink.attr('href').replace(/\s+/g,'');if(curLinkValue[0]=='/'){curLinkValue=curLinkValue.substring(1)}
if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+curLinkValue.substring(1)+"']")}}
function t830_highlightNavLinks(navLinks,sections,sectionIdTonavigationLink,clickedSectionId){var scrollPosition=$(window).scrollTop();var valueToReturn=clickedSectionId;if(sections.length!=0&&clickedSectionId==null&&sections[sections.length-1].attr('data-offset-top')>(scrollPosition+300)){navLinks.removeClass('t-active');return null}
$(sections).each(function(e){var curSection=$(this);var sectionTop=curSection.attr('data-offset-top');var id=curSection.attr('id');var navLink=sectionIdTonavigationLink[id];if(((scrollPosition+300)>=sectionTop)||(sections[0].attr("id")==id&&scrollPosition>=$(document).height()-$(window).height())){if(clickedSectionId==null&&!navLink.hasClass('t-active')){navLinks.removeClass('t-active');navLink.addClass('t-active');valueToReturn=null}else{if(clickedSectionId!=null&&id==clickedSectionId){valueToReturn=null}}
return!1}});return valueToReturn}
function t830_updateSectionsOffsets(sections){$(sections).each(function(){var curSection=$(this);curSection.attr('data-offset-top',curSection.offset().top)})}
function t849_init(recid){var rec=$('#rec'+recid);var toggler=rec.find('.t849__header');toggler.click(function(){$(this).toggleClass('t849__opened');$(this).next().slideToggle();if(window.lazy=='y'){t_lazyload_update()}})}
function t898_init(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');if(window.lazy=='y'){t_lazyload_update()}}
function t899_init(recid){t899_setMinHeight(recid);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive===!0&&$isMobile){return}
t899_setMinHeight(recid)},200));$('.t899').bind('displayChanged',function(){t899_setMinHeight(recid)});if($isMobile){$(window).on('orientationchange',function(){t899_setMinHeight(recid)})}}
function t899_getWrappers(rec){var el=document.querySelector('#rec'+rec);if(!el){return}
var wrappers=el.querySelectorAll('.t899__wrapper');return wrappers}
function t899_setMinHeight(rec){var forEach=function(array,callback,scope){for(var i=0;i<array.length;i++){callback.call(scope,i,array[i])}};var wrappers=t899_getWrappers(rec);if(wrappers){forEach(wrappers,function(index,wrapper){var symbol=wrapper.querySelector('.t899__symbol');if(symbol&&symbol.offsetHeight>wrapper.offsetHeight){wrapper.style.minHeight=symbol.offsetHeight+'px'}})}}